import { type NextPage } from "next";
import Head from "next/head";
import FilterableProductTable from "./components/FilterableProductTable";

interface Produce {
  category: string;
  price: string;
  stocked: boolean;
  name: string;
}

const Home: NextPage = () => {
  const PRODUCTS: Produce[] = [
    { category: "Fruits", price: "$1", stocked: true, name: "Apple" },
    { category: "Fruits", price: "$1", stocked: true, name: "Dragonfruit" },
    { category: "Fruits", price: "$2", stocked: false, name: "Passionfruit" },
    { category: "Vegetables", price: "$2", stocked: true, name: "Spinach" },
    { category: "Vegetables", price: "$4", stocked: false, name: "Pumpkin" },
    { category: "Vegetables", price: "$1", stocked: true, name: "Peas" },
  ];

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="p-4">
        <FilterableProductTable products={PRODUCTS} />
      </section>
    </>
  );
};

export default Home;
